services:
  - type: web
    name: heretogether
    runtime: node
    plan: free
    buildCommand: ""
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        value: https://fsuegddatlapkqnfrmxy.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
